import re
import json

# Sua string que contém um JSON no meio
text = 'Algum texto antes {"access_token":"AQAAANCMnd8BFdERjHoAwE_Cl-sBAAAAdvQ1hwE1kEOaRn4wCDHVHQAAAAACAAAAAAAQZgAAAAEAACAAAABpvc3ZFbutXMwISD61iZop5EcxUrJJcIMWDReOBfAjoQAAAAAOgAAAAAIAACAAAADXvU12FL8h9TAw1xwjKakYUcSdHP9sdkBu3GKnMbONvdACAADvtNlCvRUj0yn2pxRdorYrH1oF2h6pMtJ0hQY76xXd53aMZ6x2uXg7nUvg16hWd07Ks3HW_LLB6SYFcF9ZTcAdfMDx9dg5aGpBDPemeVJajNnfYsmHLvvz5iHv7MLAb1vmXW5VRiqTxjFIl_71bIb-Ua6aAlpIa2v666LpYBuEyjhKSvxuGRigNxLs4XgYyLM8Q1Xs9w_km2zcv-W0dR-AIQHDrlsbrrrl5UwpoJsugJj2yKe55ws4nZi9CdpmH1qrWOJIxC8P5Sp2bKiTpd1CgpDyUJyJ1QOZ9ga2BybSqgVcbjHPySBDuMJKK-52yoVHlzxgyuhvLUlkEGYvt1q8VY9XHTXXiiv_m3QYdBH5HQr0PDXrAYGHjGijDNRAOM1o4upBpmYg2jeqjx0UQGb4Vt1b8KVfcFqVSuQeYV10xqTCRtO0wZLzeCVSSyBWsTjKf4pkliYv_zjTtm_2IjVe5fMfzW9zsE5jFTL7R_9-Nme1EImG0Qd6r5gXKIOgZ5gyNTBzNSNP0MxgN7WqsniYcnoHDg4IIcHDsgJHznYhfKypcVwZ2xIJPLG3l1DAwZCFGGWoahjkyXemc-RphoWKip8G1J9Bxhopp5iY605m0wCNkf1_jqGFx736gYJNktq1bi9C4Kdhrt1ID0WfM6Ur3i5CFeO2rJDthWcXbbgDIU-_RO3JJK6YUxi3Hs899ZKRbfEX8gq1wHh6meQx-eDpxDyqWGymC6Axpbr7yLQtyOIdGYA_CHB_-tIGcuzQlYsPoGOSNDDz6g5T-BsmT3Q3MYAT5OnlTE3daovRpKWVQWhoq_I_qD7iEcHLRXrSkp8Qaygie3noPyZ-jybot--nqzzPIOsX34CwEv0bQ9e1csifcVkJSWgSdshUuN3lxGYg8jqGi0rsIHadpQCnJXmIFFP71U32jSDN-zX9VvWjh7vTtTmkWI15PhuGMHv3s3tAAAAAl98uDPiPe9KcrCB-8srtT0987dLIvmdfKGlRMUPVCx3cbU5b2kPUxINNHbH9jXz9-zdIGWR2Mk8KHam9-RYP5g","token_type":"bearer","expires_in":21599,"Role":"Admin,ViewProductionOrders,ViewAndManageProductionOrders,ViewInventoryForm,ViewAndManageInventoryForm,ViewMachineDiagnostics,ViewPickLists,ViewAndManagePickLists,ViewBatteryMonitor,ViewAndManageBatteryMonitor,ViewWaypoints,ViewOwnRights,ViewDownloadManager,ViewCouplingDialog,ViewAllowedDestinations,SelectMachine,AbortMachineTask,ManageResources,ToggleIgnoreMes,ManageForbiddenWaypoints,EnableDisableSymbolicPoint,ControlHoldRelease,FSTOPAll,TakeMachineOutOrIntoProduction,RequestPickup,StartOrStopProduction,ReleaseAnyWaypoint,StartOrStopProductionBreak,SleepAllMachines,CommandMachineFull,CommandMachineFSTOP,CommandMachineGOTO,CommandMachinePosInit,CommandMachineReturnToRoute,CommandMachineLoadUnload,EnableDisableMachine,CommandMachineSleep,ManageServerSettings,ManageUsers,ManageActiveDirectorySettings,ManageAreaFiles,ManageParameters,ManageMachineConfiguration,ManageServerLogFiles,ManageLocationPriorities,ActivateForkliftWebInterface"} Algum texto depois'

# Expressão regular para extrair o JSON
json_pattern = re.search(r'\{.*?\}', text)

if json_pattern:
    # Parse the JSON part
    json_string = json_pattern.group(0)
    data = json.loads(json_string)

    # Extrair o access_token
    access_token = data["access_token"]

    print(access_token)
else:
    print("JSON não encontrado na string.")